name: "Install"
description: "Install dependencies"

runs:
  using: "composite"
  steps:
    - name: Set up pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9.4.0

    - name: Set up node
      uses: actions/setup-node@v4
      with:
        cache: pnpm
        node-version: 20

    - name: Set up foundry
      uses: foundry-rs/foundry-toolchain@v1

    # - name: Install playwright
    #   shell: bash
    #   run: npx playwright install --with-deps chromium

    - name: Install dependencies
      shell: bash
      run: pnpm install --ignore-scripts